version: "3"

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthcare
    ports:
      - "5431:5431"

  airflow:
    image: apache/airflow
    ports:
      - "8080:8080"